doorctl/blueprints/doorctl.py
# Filename    : makersweb.py
# Author      : Jon Kelley <jon.kelley@kzoomakers.org>
# Description : Kzoomakers Door Controller
import requests
from flask import Flask, render_template, request, flash, Blueprint, redirect, url_for, current_app
import json
import datetime  # Import the datetime module
from doorctl.sharedlib.get_config import parse_uhppoted_config
import time
from dateutil import tz

from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

HEADERS = {'accept': 'application/json'}

doorctl = Blueprint('doorctl', __name__)

@doorctl.before_request
def run_on_all_routes():
    """
    Used to block requests that aren't from a specific server with the known values
    """
    # Require x-forwarded-for header to serve requests
    if current_app.config['ENABLE_PROXY_DETECTION'] == 'true':
        if 'X-Forwarded-For' not in request.headers:
            return 'Must be behind a proxy'
    # Require x-doorcontrol-security-key header with proper value
    if current_app.config['ENABLE_PROXIED_SECURIY_KEY']:
        header = request.headers.get('x-doorcontrol-security-key', None)
        if header:
            if not header == current_app.config['ENABLE_PROXIED_SECURIY_KEY']:
                return 'Invalid key for header x-doorcontrol-security-key'
        else:
            return 'Missing header x-doorcontrol-security-key'

@doorctl.route('/robots.txt')
@doorctl.route('/<path:subpath>/robots.txt')
def generate_robots_txt():
    robots_txt_content = "User-agent: *\nDisallow: /"
    return Response(robots_txt_content, content_type="text/plain")


@doorctl.route('/', methods=['GET'])
def index():
    return 'It works!'

### config editor ###
@doorctl.route('/accesscontrol/configedit')
def config_edit():
    with open('/etc/uhppoted/uhppoted.conf', 'r') as file:
        content = file.read()
    return render_template('configedit.html', content=content)

@doorctl.route('/accesscontrol/configedit/save', methods=['POST'])
def config_save():
    content = request.form.get('content')
    with open('/etc/uhppoted/uhppoted.conf', 'w') as file:
        file.write(content)
    #flash("File saved successfully!")
    return redirect('/accesscontrol/configedit')

##### controller routes #####

@doorctl.route('/accesscontrol', methods=['GET'])
@doorctl.route('/accesscontrol/', methods=['GET'])
def accesscontrol():
    return render_template('splash.html')


@doorctl.route('/accesscontrol/controller', methods=['GET'])
@doorctl.route('/accesscontrol/controller/', methods=['GET'])
def controllers_list():
    # Fetch the device time from the API
    url = f"{current_app.config['REST_ENDPOINT']}/device"
    response = requests.get(url, headers=HEADERS)

    api_config = parse_uhppoted_config('/etc/uhppoted/uhppoted.conf')
    print(api_config)
    if response.status_code == 200:
        data = response.json()
        for device in data['devices']:
            device_id = device['device-id']

            # Check if the device_id exists in 'api_config'
            if str(device_id) in api_config['devices']:
                # If it exists, update the device information in 'data'
                device_info = api_config['devices'][str(device_id)]
                device.update(device_info)
        print(data)
        return render_template('controllers.html', devices=data.get('devices', []))


##### door stuff #####

@doorctl.route('/accesscontrol/controller/<int:controller_id>/door/<int:door>/swipe', methods=['POST'])
def swipe_card(controller_id, door):
    card_number = request.json.get('card-number')
    try:
        url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/door/{door}/swipes"
        response = requests.post(url, json={"card-number": int(card_number)})
        if response.status_code in [401, 404, 405, 500]:
            error_data = response.json()
            # Flashing the error for the JS to pick up
            #flash(error_data.get('message'), 'error')
            return json.dumps({"error": "API error", "message": error_data.get('message')}), 500
        return json.dumps(response.json())
    except requests.RequestException as e:
            return json.dumps({"error": "API error"}), 500
    except Exception as e:
            return json.dumps({"error": "Unknown error", "message": f"{e}"}), 500

@doorctl.route('/accesscontrol/controller/<int:controller_id>/door/<int:door>/delay', methods=['PUT'])
def set_door_delay(controller_id, door):
    delay_time = request.json.get('delay')
    try:
        payload = {"delay": int(delay_time)}

        url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/door/{door}/delay"
        response = requests.put(url, json=payload)
        #response = requests.put(REMOTE_API_DELAY_URL.format(device_id, door), json={"delay": delay_time})
        response.raise_for_status()
        return json.dumps(response.json())
    except requests.RequestException as e:
        # Flashing the error for the JS to pick up
        #flash(str(e), 'error')
        return json.dumps({"error": f"API error, {e}"}), 500

@doorctl.route('/accesscontrol/controller/<int:controller_id>/door/<int:door>/state', methods=['PUT'])
def set_door_control(controller_id, door):
    control_state = request.json.get('control')
    try:
        url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/door/{door}/control"
        response = requests.put(url, json={"control": control_state})
        response.raise_for_status()
        return json.dumps(response.json())
    except requests.RequestException as e:
        # Flashing the error for the JS to pick up
        #flash(str(e), 'error')
        return json.dumps({"error": f"API error, {e}"}), 500


@doorctl.route('/accesscontrol/controller/<int:controller_id>/doors')
def manage_doors(controller_id):

    # Fetch device status
    url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/status"
    response = requests.get(url)
    if response.status_code == 200:
        device_status = response.json()
    else:
        device_status = {}
        flash(f"Failed to retrieve device status. Status code: {response.status_code}", "danger")

    # Fetch door details for each door
    door_info = {}
    for door_id in device_status.get('status', {}).get('door-states', {}):
        url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/door/{door_id}"
        response = requests.get(url)
        if response.status_code == 200:
            door_info[door_id] = response.json().get('door', {})
        else:
            flash(f"Failed to retrieve door {door_id} details. Status code: {response.status_code}", "danger")

    return render_template('doors.html', controller_id=controller_id, device_status=device_status, door_info=door_info)

##### device info #####
@doorctl.route('/accesscontrol/controller/<int:controller_id>/info')
def display_device_info(controller_id):
    url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}/status"
    response = requests.get(url)
    if response.status_code == 200:
        device_status = response.json()
    else:
        device_status = {}
        flash(f"Failed to retrieve device status. Status code: {response.status_code}", "danger")
    url = f"{current_app.config['REST_ENDPOINT']}/device/{controller_id}"
    response = requests.get(url)
    if response.status_code == 200:
        device_info = response.json()
    else:
        device_info = {}
        flash(f"Failed to retrieve device status. Status code: {response.status_code}", "danger")
    return render_template('controller_info.html', controller_id=controller_id, device_status=device_status, device_info=device_info)


##### events #####
def get_events(device_id):
    # Get range of events
    url = f"{current_app.config['REST_ENDPOINT']}/device/{device_id}/events/1000"
    response = requests.get(url, headers={'accept': 'application/json'})
    response_data = response.json()

    first_event = response_data['events']['first']
    last_event = response_data['events']['last']

    events = []

    # Fetch each event starting from the latest and add to the events list
    for i in range(last_event, first_event-1, -1):
        url = f"{current_app.config['REST_ENDPOINT']}/device/{device_id}/event/{i}"
        response = requests.get(url, headers={'accept': 'application/json'})
        event_data = response.json()

        event_dict = {
            "device-id": event_data["event"]["device-id"],
            "event-id": event_data["event"]["event-id"],
            "event-type": event_data["event"]["event-type"],
            "access-granted": event_data["event"]["access-granted"],
            "door-id": event_data["event"]["door-id"],
            "direction": event_data["event"]["direction"],
            "card-number": event_data["event"]["card-number"],
            "timestamp": event_data["event"]["timestamp"],
            "event-reason": event_data["event"]["event-reason"]
        }

        events.append(event_dict)

    return {"events": events}

@doorctl.route('/accesscontrol/controller/<int:controller_id>/events')
def device_events(controller_id):
    event_data = get_events(device_id=controller_id)
    return render_template('events.html', events=event_data, controller_id=controller_id)


##### time profiles #####
@doorctl.route("/accesscontrol/controller//<int:controller_id>/add_time_profile", methods=["GET", "POST"])
def add_time_profile(controller_id):
    if request.method == "POST":
        # Handle form submission for creating a new time profile
        time_profile_id = request.form.get("time_profile_id")
        start_date = request.form.get("start_date")
        end_date = request.form.get("end_date")
        weekdays = request.form.get("weekdays")
        segment_start = request.form.get("segment_start")
        segment_end = request.form.get("segment_end")

        # Create a dictionary with the time profile data

doorctl/templates/configedit.html
<head>
	<!-- Core CSS -->
	<link rel="stylesheet" href="path_to_codemirror/lib/codemirror.css">

	<!-- Vim KeyMap -->
	<script src="path_to_codemirror/keymap/vim.js"></script>

	<!-- Mode (e.g., JavaScript) -->
	<script src="path_to_codemirror/mode/javascript/javascript.js"></script>

	<!-- Theme (e.g., "monokai") -->
	<link rel="stylesheet" href="path_to_codemirror/theme/monokai.css">

	<!-- Core JS -->
	<script src="path_to_codemirror/lib/codemirror.js"></script>
</head>

<body>
	<form action="/accesscontrol/configedit/save" method="post">
	    <textarea name="content" id="editor">{{ content }}</textarea>
	    <button type="submit">Save</button>
	</form>

	<script>

	    var editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
	        mode: "text",
	        lineNumbers: true,
	        keyMap: "vim",
	        theme: "vim"
	    });
	    editor.setSize("800px", "600px");
	</script>
</body>

doorctl/templates/controller_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Device Information</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Device Information</h1>
        <div class="row">
            <div class="col-md-6">
                <h2>Status</h2>
                <ul class="list-group">
                    <li class="list-group-item">Device ID: {{ device_status['device-id'] }}</li>
                    <li class="list-group-item">System Datetime: {{ device_status['status']['system-datetime'] }}</li>
                    <li class="list-group-item">System Error: {{ device_status['status']['system-error'] }}</li>
                    <li class="list-group-item">Input State: {{ device_status['status']['input-state'] }}</li>
                    <li class="list-group-item">Relay State: {{ device_status['status']['relay-state'] }}</li>
                    <li class="list-group-item">Sequence ID: {{ device_status['status']['sequence-id'] }}</li>
                    <li class="list-group-item">Special Info: {{ device_status['status']['special-info'] }}</li>
                    <li class="list-group-item">Door States:
                        <ul>
                            {% for door_id, state in device_status['status']['door-states'].items() %}
                                <li>Door {{ door_id }}: {{ 'Open' if state else 'Closed' }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="list-group-item">Door Buttons:
                        <ul>
                            {% for door_id, state in device_status['status']['door-buttons'].items() %}
                                <li>Door {{ door_id }}: {{ 'Pressed' if state else 'Not Pressed' }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                <h2>Device Info</h2>
                <ul class="list-group">
                    <li class="list-group-item">Device Type: {{ device_info['device']['device-type'] }}</li>
                    <li class="list-group-item">IP Address: {{ device_info['device']['ip-address'] }}</li>
                    <li class="list-group-item">Subnet Mask: {{ device_info['device']['subnet-mask'] }}</li>
                    <li class="list-group-item">Gateway Address: {{ device_info['device']['gateway-address'] }}</li>
                    <li class="list-group-item">MAC Address: {{ device_info['device']['mac-address'] }}</li>
                    <li class="list-group-item">Version: {{ device_info['device']['version'] }}</li>
                    <li class="list-group-item">Date: {{ device_info['device']['date'] }}</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.device_events', controller_id=controller_id) }}" class="btn btn-primary active">
                Controller Event Log
            </a>
        </div>
    </div>

    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.controller_manage', controller_id=controller_id) }}" class="btn btn-secondary active">
                Back to controller
            </a>
        </div>
    </div>
    <!-- Include Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-B5gt1jrGC7Jh4AgTPSdUtOBvfO8sh+5z5n2x5c5l5p5L5f5r5d5u5g5l5i5D5m5E5a5x5P5B5v5i5O5F5h5T5T5H5a5E5u5M5H5x5f5l5l5A5b5v5Y5l5V5U5L5Q5h5L5g5N5f5D5O5L5E5/" crossorigin="anonymous"></script>
</body>
</html>

doorctl/templates/controller_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UHPPOTE Devices</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css">
</head>
<body>

    <div class="container mt-4">
        <h1 class="mt-5">Controller {{ controller_id }}</h1>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.show_cards', controller_id=controller_id) }}" class="btn btn-primary active">
                Manage Cards
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.manage_doors', controller_id=controller_id) }}" class="btn btn-primary active">
                Manage Doors
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.get_time_profiles', controller_id=controller_id) }}" class="btn btn-primary active">
                Manage Time Profiles
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.display_device_info', controller_id=controller_id) }}" class="btn btn-primary active">
                Device Info
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.set_device_time', controller_id=controller_id) }}" class="btn btn-primary active">
                Set Time
            </a>
        </div>
    </div>
    <div class="container mt-5">
        <h1>Last Event</h1>
        <table class="table">
        {% if event %}
            <thead>
                <tr>
                    <th>Event ID</th>
                    <th>Card#</th>
                    <th>Door ID</th>
                    <th>Event Type</th>
                    <th>Access Granted</th>
                    <th>Direction</th>
                    <th>Timestamp</th>
                    <th>Event Reason</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ event['event-id'] }}</td>
                    <td>{{ event['card-number'] }}</td>
                    <td>{{ event['door-id'] }}</td>
                    <td>{{ event['event-type-text'] }}</td>
                    <td>{{ "Yes" if event['access-granted'] else "<span class=\"badge bg-danger\">DENIED</span>"|safe }}</td>
                    <td>{{ event['direction-text'] }}</td>
                    <td>{{ event['timestamp'] }}</td>
                    <td>{{ event['event-reason-text'] }}</td>
                </tr>
            </tbody>
        {% else %}
            <tr>
                <td colspan="8">No events found</td>
            </tr>
        {% endif %}
        </table>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.device_events', controller_id=controller_id) }}" class="btn btn-primary active">
                Full Event Log
            </a>
        </div>
    </div>
    <div class="container mt-5">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.accesscontrol') }}" class="btn btn-secondary active">
                Controller List
            </a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

doorctl/templates/get_time_profiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Time Profiles</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Time Profiles</h1>
        <!-- Display flash messages if any -->
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
               <div class="alert alert-{{ category }}" role="alert"> {{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Weekdays</th>
                    <th>Segments</th>
                </tr>
            </thead>
            <tbody>
                {% for time_profile in time_profiles['profiles'] %}
                <tr>
                    <td>{{ time_profile.id }}</td>
                    <td>{{ time_profile['start-date'] }}</td>
                    <td>{{ time_profile['end-date'] }}</td>
                    <td>{{ time_profile.weekdays }}</td>
                    <td>{{ time_profile.segments }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.add_time_profile', controller_id=controller_id) }}" class="btn btn-primary active">
                   Add Time Profile
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <div class="btn-group">
            <a href="{{ url_for('doorctl.controller_manage', controller_id=controller_id) }}" class="btn btn-secondary active">
                Back to controller
            </a>
        </div>
    </div>
    <!-- Include Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

doorctl/templates/splash.html
<head>
	<style>









        * {
            box-sizing: border-box;
        }
        body {
        	font-family: arial, sans-serif;
            overflow: hidden;
            margin: 0;
            padding: 0;
            background-color: #443535;
            background-image: linear-gradient(45deg, #536058 25%, transparent 25%, rgba(242, 236, 236, 0) 75%, #49554E 75%, #536159), linear-gradient(-45deg, #4D5A53 25%, transparent 25%, transparent 75%, #536058 75%, #4C5851);
            background-size: 100px 100px;
        }
        .clock-wrapper {
            background: #96D2D0;
            position: absolute;
            bottom: 480px;
            left: 530px;
            border: 10px solid #eee;
            box-shadow: 0 0 0 5px #D4D1D1, 0 0 0 12px #DEDDDD, 0 0 12px 14px grey;
            width: 250px;
            height: 250px;
            border-radius: 50%;
            transform: rotateX(180deg) scale(0.5);
        }
        .dot1,
        .dot2,
        .dot3,
        .dot4 {
            border: 1px solid lightgrey;
            height: 12px;
            width: 12px;
            background: white;
            border-radius: 50%;
            position: absolute;
        }
        .dot1 {
            left: 48%;
            top: 0;
        }
        .dot2 {
            right: 0;
            top: 47%;
        }
        .dot3 {
            left: 48%;
            bottom: 0;
        }
        .dot4 {
            left: 0;
            top: 47%;
        }
        .seconds-arrow {
            margin: 0;
            padding: 0;
            background: red;
            height: 120px;
            width: 3px;
            position: absolute;
            transform-origin: center top;
            top: 50%;
            left: 50%;
            border-bottom-left-radius: 50%;
            border-bottom-right-radius: 50%;
            margin-left: -2px;
        }
        .circle-sm {
            background: red;
            height: 20px;
            width: 20px;
            border-radius: 50%;
            position: absolute;
            top: 48%;
            left: 47%;
            box-shadow: 5px 1px 10px #888888;
        }
        .minute-arrow {
            background: #444;
            border-bottom-left-radius: 50%;
            border-bottom-right-radius: 50%;
            height: 120px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform-origin: center top;
            transition: transform 3s;
            width: 6px;
        }
        .hour-arrow {
            background: black;
            border-bottom-left-radius: 50%;
            border-bottom-right-radius: 50%;
            height: 90px;
            position: absolute;
            top: 52%;
            left: 50%;
            transform-origin: center top;
            transition: transform 3s;
            width: 9px;
        }
        .seconds-arrow {
            box-shadow: 4px 4px 3px #888888;
            animation: 60s clock-arrow-spin steps(60, end) infinite;
        }
        .minute-arrow {
            animation: 3600s clock-arrow-spin steps(60, end) infinite;
        }
        .hour-arrow {
            animation: 86400 clock-arrow-spin steps(60, end) infinite;
        }
        .door {
            position: absolute;
            bottom: 95px;
            left: 500px;
        }
        .door-frame {
            position: absolute;
            right: 50px;
            bottom: 20px;
            width: 200px;
            height: 400px;
            background-color: rgba(207, 155, 164, 0.6);
            border: 15px solid rgb(45, 26, 26);
            border-bottom: 5px solid rgb(45, 26, 26);
            border-left: 30px solid rgb(54, 17, 17);
            box-shadow: 0 0 0 10px #C7C3C3, 0 0 0 15px #E6E2E2;
        }
        .door-open {
            position: absolute;
            right: 50px;
            bottom: 20px;
            width: 173px;
            height: 400px;
            border-top: 15px solid transparent;
            border-bottom: 15px solid transparent;
            border-left: 160px solid rgb(54, 17, 17);
            border-right: 15px solid transparent;
            animation: door-opening 5s ease 0s infinite alternate;
        }
        .inner-door-knob {
            width: 20px;
            height: 5px;
            border-radius: 6px;
            background-color: #965322;
            position: absolute;
            top: 50%;
            right: 25px;
        }
        footer {
            height: 100px;
            width: 100%;
            background-image: linear-gradient(to bottom left, #6C7D73 20%, #262D29 100%);
            bottom: 0;
            position: absolute;
            z-index: -1;
            border-top: 3px solid #443535;
        }
        .sofa-wrapper {
            position: absolute;
            bottom: 352px;
            left: 800px;
            transform: scale(1.25, 1.1);
        }
        .sofa-top {
            position: absolute;
            width: 240px;
            height: 100px;
            background-color: #EEDEDE;
            border-top-left-radius: 60px;
            border-top-right-radius: 60px;
            border: 2px solid grey;
            z-index: 1;
        }
        .sofa-top:before,
        .sofa-top:after {
            top: 40px;
            content: " ";
            width: 50px;
            height: 100px;
            background-color: #E2CCCC;
            position: absolute;
            border-radius: 50px;
            border: 1px solid grey;
        }
        .sofa-top:before {
            left: -5px;
            transform: rotate(-10deg);
        }
        .sofa-top:after {
            right: -5px;
            transform: rotate(10deg);
        }
        .sofa-bottom1 {
            position: absolute;
            width: 244px;
            height: 55px;
            background-color: #EEDEDE;
            top: 142px;
            border-radius: 40px;
            border: 2px solid grey;
        }
        .sofa-bottom1:before {
            content: " ";
            position: absolute;
            background-color: #F2ECEC;
            height: 44px;
            width: 184px;
            top: -45px;
            left: 25px;
        }
        .sofa-bottom1:after {
            content: " ";
            position: absolute;
            background-color: grey;
            height: 2px;
            width: 96%;
            bottom: 46%;
            left: 5px;
        }
        .sofa-bottom2 {
            position: absolute;
            top: 197px;
            left: 30px;
            width: 184px;
        }
        .sofa-bottom2:before,
        .sofa-bottom2:after {
            position: absolute;
            content: " ";
            width: 23px;
            height: 32px;
            background-color: #958E8E;
            border-radius: 10px;
            bottom: -33px;
            border: 1px solid grey;
            border-top: 1px solid transparent;
            border-top-left-radius: 1px;
            border-top-right-radius: 1px;
        }
        .sofa-bottom2:before {
            left: 10px;
        }
        .sofa-bottom2:after {
            right: 10px;
        }
        .portrait {
            position: absolute;
            left: 900px;
            bottom: 450px;
            width: 130px;
            height: 160px;
            /* background: url('https://s-media-cache-ak0.pinimg.com/564x/07/21/15/0721158c75b17f7ada105db9f8b4e32f.jpg'); */
            background: url('https://kzoomakers.org/static/img/team/zach.webp');
            animation: picture-falling 5s;
            opacity: 1;
            box-shadow: 0 0 0 10px #C7C3C3, 0 0 0 15px #E6E2E2, 0 0 25px 15px grey;
          background-size: cover;
        }
        /*   -------------------   CSS ANIMATIONS   -------------------   */
        
        @-webkit-keyframes clock-arrow-spin {
            100% {
                transform: rotate(-360deg);
            }
        }
        /*   ------------------------------------------------------    */
        
        @keyframes picture-falling {
            0% {
                opacity: 1;
            }
            15% {
                transform: rotate(0deg) translateX(0);
                opacity: 1;
                animation-timing-function: cubic-bezier(.07, 2.02, .67, .57);
            }
            30% {
                transform: translateY(100px) rotate(90deg);
                animation-timing-function: cubic-bezier(.13, .84, .82, 1);
            }
            50% {
                transform: translateX(20px) translateY(100px) rotateY(90deg, 20deg);
            }
            60% {
                transform: translateY(1000px) rotate(90deg);
                opacity: 1;
                z-index: -10;
                box-shadow: 0 0 0 10px #C7C3C3, 0 0 0 15px #E6E2E2;
            }
            70% {
                transform: translateY(1000px) otate(90deg);
                opacity: 1;
            }
        }
        /*   ------------------------------------------------------    */
        
        @-webkit-keyframes door-opening {
            from {
                -webkit-transform: perspective(500) rotateY(-5deg);
                -webkit-transform-origin: 0% 0%;
            }
            to {
                -webkit-transform: perspective(500) rotateY(-165deg);
                -webkit-transform-origin: 0% 0%;
            }
        }
        /*   ------------------------------------------------------    */
	</style>
</head>
<body>

    <div class="door">
        <div class="door-frame"></div>
        <div class="door-open">
            <div class="inner-door-knob"></div>
        </div>
    </div>

    <div class="clock-wrapper">
        <div class="dot1"></div>
        <div class="dot2"></div>
        <div class="dot3"></div>
        <div class="dot4"></div>
        <div class="seconds-arrow"></div>
        <div class="minute-arrow"> </div>
        <div class="hour-arrow"></div>
        <div class="circle-sm"></div>
    </div>

    <div class="portrait"></div>

    <div class="sofa-wrapper">
        <div class="sofa-top"></div>
        <div class="sofa-bottom1"></div>
        <div class="sofa-bottom2"></div>
    </div>

  <footer class="footer"><center><h1>Copyright 2023 Jonathan Kelley</h1></center>
  </footer>
  <script>
	  	setTimeout(function(){
	    window.location.href = "{{ url_for('doorctl.controllers_list') }}";
	}, 3000); // 5000 milliseconds = 5 seconds
	</script>
</body>